### ISSUE TITLE
Build fails when patching gwt-2.9.0

### ISSUE THREAD

**Issue by tcalico** [bartoszek/AUR-rstudio-desktop-git#3]
Basically what the title says, output follows:

Starting prepare()...
Checking patch src/gwt/build.xml...
error: while searching for:
\</target>

   \
   \<property name="node.version" value="10.19.0"/>
   \<property name="node.dir" value="../../dependencies/common/node/${node.version}"/>
   \<condition property="node.bin" value="../../../${node.dir}/bin/node">
     \<not>
        \<os family="windows" />
    \</not>
   \</condition>
   \<condition property="node.bin" value="${node.dir}/node.exe">
     \<os family="windows" />
   </condition>

   \
   <\available
      property="node.bin"
      value="/opt/rstudio-tools/dependencies/common/node/${node.version}/bin/node"
      file="/opt/rstudio-tools/dependencies/common/node/${node.version}/bin/node"/>

   \<property name="panmirror.dir" value="./panmirror/src/editor"/>
   \<property name="panmirror.build.dir" value="./www/js/panmirror"/>

error: patch failed: src/gwt/build.xml:82
error: src/gwt/build.xml: patch does not apply
==> ERROR: A failure occurred in prepare().
    Aborting...
 -> error making: rstudio-desktop-git

**Comment by bartoszek** [comment]
Thanks for poking me about it, I'm currently away from my ring and can't really test/post updates, sorry. ~Untill I'm back could you please try it gwt patch is still required? Remove it from prepare() function and post the error message if any.~
The gwt error is due to outdated `nodejs-external.patch` you should be able to build rstudio with bundled nodejs by removing this line in PKGBUILD:
https://github.com/bartoszek/AUR-rstudio-desktop-git/blob/master/PKGBUILD#L42
I'll try to update it as soon as I'm back.
Related to #2

**Comment by tcalico** [comment]
Just tried that and got:
`  -> Downloading gwt-2.9.0.zip...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 94.4M  100 94.4M    0     0   9.7M      0  0:00:09  0:00:09 --:--:-- 11.1M
==> ERROR: qt.conf was not found in the build directory and is not a URL.
`

**Comment by tcalico** [comment]
So, it still fails at building after your proposed fix.
Here is the code it is spitting out.

```
BUILD FAILED
/mnt/temp/AUR-rstudio-desktop-git/src/rstudio/src/gwt/build.xml:146: The following error occurred while executing this line:
/mnt/temp/AUR-rstudio-desktop-git/src/rstudio/src/gwt/build.xml:110: Execute failed: java.io.IOException: Cannot run program "../../../../../dependencies/common/node/16.14.0/bin/node" (in directory "/mnt/temp/AUR-rstudio-desktop-git/src/rstudio/src/gwt/panmirror/src/editor"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:621)

```
